### ISSUE TITLE
Support Python 3.10 -- find replacement for stdlib_list

### ISSUE THREAD

**Issue by szabi** [thebjorn/pydeps#171]
`stdlib_list` is an archived project. The last Python version supported is 3.9; and >=3.10 will never be added.

Currently, using pydeps with Python 3.10 falls back to using the 3.9 standard lib listing. That's a viable workaround for now, but with growing stdlib differences with every Python version (the actual *current* stable version is already 3.11 -- two versions newer) the fallback will be less and less 'correct' and will contain more and more errors.

For `pydeps` to stay useful and relevant, it seems utmost important to find a replacement for stdlib_list or take over the maintenance of the closed/archived project [python-stdlib-list](https://github.com/jackmaney/python-stdlib-list).

**Comment by thebjorn** [comment]
This is actually not a huge problem for pydeps. The current stdlib_list package is (and will probably always be) on PyPI and is quite comprehensive for the python versions it supports. Pydeps will use the lists from the latest supported python version from stdlib_list, and since new stdlib modules are added rather infrequently to python this works well.

The modules that are in 3.11 but not in stdlib_list's 3.9 are 
```
{'_contextvars', '_tkinter', '_socket', '_tokenize', 'tomllib', '_symtable', '_warnings', '_md5', '_posixsubprocess', '_random', '_sre', '_sha256', '_struct', '_locale', '_codecs', '_codecs_hk', '_xxsubinterpreters', '_bisect', '_posixshmem', '_sha1', '_operator', '_sqlite3', '_pickle', '_string', 'pyexpat', '_codecs_cn', '_codecs_jp', '_functools', '_io', '_codecs_tw', '_statistics', '_winapi', '_bz2', '_curses_panel', '_abc', '_dbm', '_stat', '_decimal', '_codecs_kr', '_signal', 'xxsubtype', '_msi', '_multibytecodec', 'nt', '_crypt', '_frozen_importlib', '_overlapped', '_csv', '_sha512', '_ssl', '_tracemalloc', '_queue', '_ast', '_curses', '_lzma', '_opcode', '_blake2', '_scproxy', '_zoneinfo', '_uuid', '_imp', '_typing', '_sha3', '_ctypes', '_heapq', '_gdbm', '_weakref', '_frozen_importlib_external', '_multiprocessing', '_lsprof', '_collections', '_hashlib', '_asyncio', '_elementtree', '_datetime', '_codecs_iso2022', '_json'}
```
Since the list returned by `list(sys.stdlib_module_names | set(sys.builtin_module_names))` only contains top-level modules, there are 656 modules that are listed in stdlib_list's 3.9 modules that are not returned from py3.11. I'm not sure there is an efficient way of populating these.

The dev/py310-native-stdlib-list branch (https://github.com/thebjorn/pydeps/tree/dev/py310-native-stdlib-list) implements the py310+ PR to stdlib_list (https://github.com/jackmaney/python-stdlib-list/pull/56).

**Comment by szabi** [comment]
Given that stdlib-list was archved with "This repo is now archived. I no longer have the spoons to maintain this in my spare time." (from README.md) I guess, even PRs won't be merged.

You could try contacting @jackmaney and maybe fork stdlib-list and learn how he compiled the complete list (or even take over maintenance).

The actual effort to maintaining it might be well worth for pydeps to exist: new Python versions come around once a year, in October, so the maintenance effort likely is limited.

**Comment by thebjorn** [comment]
I'm afraid you might seriously underestimate the effort it takes to maintain a project like stdlib_list, which needs to always be ahead of new python versions and the challenges that poses with installations of alpha/beta/rc versions both locally and in the CI.

If you want to take it on though, I'm sure everyone would be delighted :-)  Documentation for how the list was compiled, as well as code for doing it is in the repo.

For pydeps, I'm much more likely to vendorize the resulting lists than taking over maintenance - but since Python versions < 3.10 are already covered (and unlikely to change, since it goes against python's non-current micro-version release policy) there really is no practical point.

Of course, if you have a real issue, and not just a fear of future viability, I would be happy to look at it.

**Comment by szabi** [comment]
I absolutely believe that I am underestimating it. However,  I would have assumed that for keeping pydeps productive, as a "MVP" it would suffice to keep up to date with stable versions, which come out once a year with the current schedule.

Vendorizing the list does not solve the problem in so far, that the list still has to be compiled somehow (and stdlib-list seems to be up to the task per se, unless it falls behind and stays unmaintained for too long a time).

I don't quite get the "there really is no practical point", as neither the current nor the last-but-current versions are supported: The last supported version, 3.9 is already beyond it's end of full support date (2022-05-17).

I fully understand that you don't want to take over the maintenance of it, I am certainly not trying to convince or urge you, but then, I guess, one has to think about other ways to procure the list (for vendorizing).

**Comment by stefan6419846** [comment]
As already mentioned in https://github.com/thebjorn/pydeps/issues/95#issuecomment-1380389179, Python since version 3.10 does have in-built support for retrieving such a list - it just has to be evaluated to which extent this actually matches with the `stdlib_list` data ([3.10.txt](https://github.com/thebjorn/pydeps/files/11100412/3.10.txt) [3.11.txt](https://github.com/thebjorn/pydeps/files/11100413/3.11.txt)).

**Comment by szabi** [comment]
Just for reference, `stdlib_list` is no longer archived and unmaintained, but has been transferred to the pypi team: https://github.com/pypi/stdlib-list

**Comment by thebjorn** [comment]
@szabi yes, I'm aware :-)

https://github.com/thebjorn/pydeps/commit/ba358d0456aed9cf6bac4e04e552ea42dd7f15eb
