### ISSUE TITLE
empty result with WARNING: SKIPPING ILLEGAL MODULE_NAME: D:.test.a

### ISSUE THREAD

**Issue by Yunchuan-Xu** [thebjorn/pydeps#209]
[Environment]
```powershell
(venv) PS D:\> pydeps --version
pydeps v1.12.18
```

[Directory Structure]
D:\test\
  ├─ a.py
  └─ b.py

[Case]
```powershell
(venv) PS D:\> pydeps .\test\
dummymodule.py:139: WARNING: SKIPPING ILLEGAL MODULE_NAME: D:.test.a
dummymodule.py:139: WARNING: SKIPPING ILLEGAL MODULE_NAME: D:.test.b
```

The output svg does not contain any graph elements.

**Comment by thebjorn** [comment]
Hi @Yunchuan-Xu  and thank you for your interest in pydeps.

The test directory is not a valid module (you'll need an `__init__.py` file). To get any output you'll need to have imports in the files, eg. (`https://pypi.org/project/yamldirs/`): 

```shell
c:\srv\tmp\pydeps209> yamldirs test
test:
  __init__.py: ''
  a.py: |
    from . import b
  b.py: |
    from . import a
c:\srv\tmp\pydeps209> pydeps -Tpng test
```
(`-Tpng` because github doesn't like pasted svgs..) gives me

![test](https://github.com/thebjorn/pydeps/assets/1193143/382037b5-c4d1-40b6-bc7a-db8fc7d166e5)

**Comment by Yunchuan-Xu** [comment]
@thebjorn Now it works. Thanks for your explanation!
