### ISSUE TITLE
Config Options

### ISSUE THREAD

**Issue by EverWinter23** [thebjorn/pydeps#30]
So I have my package, lets call it `colors`, which I have installed inside a virtualenv. It depends on external packages like `numpy`, `scipy`, `and_others`. Is there a way in which for `colors` it explores
all there is to explore, but once it hits external dependencies like `numpy` it stops, but plots them,
without going inside `numpy`.

So I can do this when I install my package in a virtualenv in which I am yet to install any external dependency. And I have a file say:

```python
file: foo.py

from colors import purple
from colors.palette import something_pretentious
```
```python
file: colors.palette

imports numpy
```
And then when I run `pydeps --max-bacon=0 foo.py --include-missing`, can I get the same output
when I have `numpy` installed inside the virtualenv? So for `colors` it just goes and gets all deps
inside that package, but when it arrives to other packages, it just plots a node for them and then stops.

PS: Great module.

**Comment by thebjorn** [comment]
There is no specific option to stop at the mention of external packages, but all you should need is: `pydeps --include-missing foo.py`.  The default `--max-bacon=2` means this module + the first level of external modules. 

Note that if your code imports both `numpy.a` and `numpy.b`, and `numpy.b` imports `numpy.a`, then that relationship is also included in the graph. E.g. this was produced by `pydeps dkrepo\gitrepo.py`. Notice how the top node (`dkrunners.runexceptions`) also points to another external module (`dkrunners.runner`) since both are imported by `dkrepo.gitrepo`:

![dkrepo_gitrepo](https://user-images.githubusercontent.com/1193143/62420601-25ad2f80-b695-11e9-83e9-b2bd2cc004eb.png)
