### ISSUE TITLE
Anyway to create artificial dependencies?

### ISSUE THREAD

**Issue by ifasina** [thebjorn/pydeps#5]
This library is awesome! I was wondering if there was a create artificial dependencies so that we can use this library for other things rather than just python dependencies. For example, rather than dependency graph for python, one for C, or NodeJS. Basically making this library universal. Thanks!

**Comment by thebjorn** [comment]
I can see how that would be useful. One way to do it with the existing `pydeps` would be to create a Python source structure corresponding to your target language. E.g. for C you'd have to write a preprocessor that creates `foo/bar/baz.py` from `foo/bar/baz.c` and converts `#include` to `import`.  It should be doable, but...

`pydeps` uses a patched version of Python's `modulefinder.py` module which works by reading the bytecode of the "root" file looking for import op-codes (and then recursively reading each imported file). This is very Python specific, but an attempt has been made to generate more abstract datastructures after the initial pass.

It could be possible to create a better defined interface between the raw dependency finder and the rest of the system, but it turns out that is just half the problem. For any non-trivial program, the raw dependency graph is *huge*. You're rarely interested in the Python stdlib dependency graph when looking at your own module yet it turns out to be difficult to avoid it - iow, you'll need a language-sensitive dependency graph pruner.

**Comment by ifasina** [comment]
Yeah I see what you mean. Thanks for responding!
